cert_pem_path: certs/host.crt
private_key_path: certs/host.key

meta_data_path: templates/meta-data.yaml.j2
user_data_path: templates/user-data.yaml.j2
site_cert_path: certs/site.crt

# fsmap:
#   bootstrap: bootstrap

sshkeys:
  ubuntu:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLqmmfByjFuStwUpyIc7dcn2nOV/q+LDTzAn/32zbc/ service@carolina"
